language: clojure

jdk:
  - oraclejdk8

script:
  - lein midje

before_install:
 - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | gpg --import; fi
 - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust; fi

deploy:
 - provider: script
   skip_cleanup: true
   script: scripts/deploy.sh
   on:
     tags: true

 - provider: script
   skip_cleanup: true
   script: scripts/deploy.sh
   on:
     branch: master
